spring:
  profiles:
    active: pro
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  session:
    store-type: jdbc

#  cache:
#    type: ehcache
#    ehcache:
#      config: ehcache.xml
server:
  port: 8088
  servlet:
    session:
      timeout: 1800
